name = "wysiwyg-pdf-backend"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
routes = [
	{ pattern = "pdf.wysiwyg-doc.com", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "wysiwyg-pdf-db"
database_id = "ebca882c-a6db-44fb-8051-8b05d9153995"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "wysiwyg-pdf-asset"

[triggers]
crons = ["*/30 * * * *"] # Every 30 minutes

[assets]
directory = "../frontend/dist"
binding = "ASSETS"
